AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    swagger-ui-sam-app
    Sample Serverless Application Model for Swagger UI site

Globals:
    Function:
        Timeout: 10

Resources:
    SwaggerUiFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: swagger_ui/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                SwaggerUi:
                    Type: Api
                    Properties:
                        Path: /doc
                        Method: get

    SwaggerJsonFetcherFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: swagger_json_fetcher/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Events:
                SwaggerJsonFetcher:
                    Type: Api
                    Properties:
                        Path: /jsonFiles/{fileName}
                        Method: get

Outputs:
    SwaggerUiApi:
        Description: "API Gateway endpoint URL for Prod stage for Hello World function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/doc/"
    SwaggerUiFunction:
        Description: "Swagger UI Lambda Function ARN"
        Value: !GetAtt SwaggerUiFunction.Arn
    SwaggerJsonFetcherApi:
        Description: "API Gateway endpoint URL for Prod stage for SwaggerJsonFetcher function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/doc/"
    SwaggerJsonFetcherFunction:
        Description: "Swagger Json Fetcher Lambda Function ARN"
        Value: !GetAtt SwaggerJsonFetcherFunction.Arn
    SwaggerUiHostIamRole:
        Description: "Implicit IAM Role created for Swagger UI function"
        Value: !GetAtt SwaggerUiHostIamRole.Arn
